name: Deploy

on:
    # push:
    #     branches:
    #         - main
    workflow_dispatch:
    workflow_run:
        workflows: ['Run Tests']
        types: [completed]

jobs:
    on-success:
        name: "Deploy on VPS"
        runs-on: ubuntu-latest
        steps:
          - run: echo "Test workflow finished successfully"
    
    on-failure:
        name: "Let see if this runs"
        runs-on: ubuntu-latest
        steps:
          - run : echo "This should print even if the workflow didn't failed"