name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_run:
        workflows: ['test']
        types: [completed]

jobs:
    on-success:
        name: "Deploy on VPS"
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
          - run: echo "Test workflow finished successfully"